'use strict';

// CHANGE_PASSWORD
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';
// LOST_PASSWORD
export const LOST_PASSWORD_REQUEST = 'LOST_PASSWORD_REQUEST';
export const LOST_PASSWORD_SUCCESS = 'LOST_PASSWORD_SUCCESS';
export const LOST_PASSWORD_FAILURE = 'LOST_PASSWORD_FAILURE';
// RESET_PASSWORD
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';
// VERIFY_USER
export const VERIFY_USER_REQUEST = 'VERIFY_USER_REQUEST';
export const VERIFY_USER_SUCCESS = 'VERIFY_USER_SUCCESS';
export const VERIFY_USER_FAILURE = 'VERIFY_USER_FAILURE';
